### ISSUE TITLE
Better usability on login

### ISSUE THREAD

**Issue by Mimickal** [tair/toastdos-front#37]
Currently whenever anybody logs in, they're brought to the homepage. New users may not notice the "Submission" link appear in the upper left hand corner.

If a user logs in with the "Researcher" role, they should either be brought directly to the submission page, or the homepage should change to make the link to the submission page more obvious

If a user logs in with the "Curator" role, they should either be brought directly to the curation list view page, or the homepage should change to show submissions pending curation.

**Comment by GavinNishizawa** [comment]
This will be resolved in tair/toastdos-back#235
