### ISSUE TITLE
ToastDos / GOAT does not show up on IE in MSWindows

### ISSUE THREAD

**Issue by monicacecilia** [tair/toastdos-front#69]
Hello friends, 

Just a heads up: we were trying to play with GOAT on IE (v11.0.9) running on MSWindows and we only got a green screen. No pages were visible. 

I hope this is helpful.

**Comment by GavinNishizawa** [comment]
We will resolve this issue by displaying a message to the user that they should use another browser to access the application.

**Comment by GavinNishizawa** [comment]
See tair/toastdos-back#234 for updates.
