### ISSUE TITLE
Unable to review after adding all required fields

### ISSUE THREAD

**Issue by monicacecilia** [tair/toastdos-front#70]
Hello, 

We came across another hiccup.

While running a demo of GOAT, we were unable to 'review' the annotations, despite having one publication, one gene, and three annotations. 
The annotations included a Protein-Protein interaction, as well as a GO term, in addition to the publication and 2 gene names. 
We started deleting annotations until only the protein-protein interaction was left and the 'review submission' button showed up.

**Comment by tberardini** [comment]
I tried to replicate this behavior on both Chrome and Firefox and was unable to.  I think what happened is that one of the annotations didn't have a method filled in and that's what caused the hiccup.  The message at the bottom of the page that currently says

" Please ensure there is at least a publication, 1 gene, and 1 annotation"

could be modified to say 

" Please ensure there is at least a publication, 1 gene, and 1 annotation.  For all non-comment annotations, please make sure there is a method is entered."

Alternatively, and perhaps, better, the 'missing' field could be highlighted or shaded.

**Comment by GavinNishizawa** [comment]
This will be resolved in tair/toastdos-back#231
